/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripRouteImport } from './routes/trip'
import { Route as ShareRouteImport } from './routes/share'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ParsingRouteImport } from './routes/parsing'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as IndexRouteImport } from './routes/index'

const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsingRoute = ParsingRouteImport.update({
  id: '/parsing',
  path: '/parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/inspiration': typeof InspirationRoute
  '/my-trips': typeof MyTripsRoute
  '/parsing': typeof ParsingRoute
  '/quiz': typeof QuizRoute
  '/share': typeof ShareRoute
  '/trip': typeof TripRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/inspiration': typeof InspirationRoute
  '/my-trips': typeof MyTripsRoute
  '/parsing': typeof ParsingRoute
  '/quiz': typeof QuizRoute
  '/share': typeof ShareRoute
  '/trip': typeof TripRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/explore': typeof ExploreRoute
  '/import': typeof ImportRoute
  '/inspiration': typeof InspirationRoute
  '/my-trips': typeof MyTripsRoute
  '/parsing': typeof ParsingRoute
  '/quiz': typeof QuizRoute
  '/share': typeof ShareRoute
  '/trip': typeof TripRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations'
    | '/explore'
    | '/import'
    | '/inspiration'
    | '/my-trips'
    | '/parsing'
    | '/quiz'
    | '/share'
    | '/trip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/destinations'
    | '/explore'
    | '/import'
    | '/inspiration'
    | '/my-trips'
    | '/parsing'
    | '/quiz'
    | '/share'
    | '/trip'
  id:
    | '__root__'
    | '/'
    | '/destinations'
    | '/explore'
    | '/import'
    | '/inspiration'
    | '/my-trips'
    | '/parsing'
    | '/quiz'
    | '/share'
    | '/trip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRoute
  ExploreRoute: typeof ExploreRoute
  ImportRoute: typeof ImportRoute
  InspirationRoute: typeof InspirationRoute
  MyTripsRoute: typeof MyTripsRoute
  ParsingRoute: typeof ParsingRoute
  QuizRoute: typeof QuizRoute
  ShareRoute: typeof ShareRoute
  TripRoute: typeof TripRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsing': {
      id: '/parsing'
      path: '/parsing'
      fullPath: '/parsing'
      preLoaderRoute: typeof ParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRoute,
  ExploreRoute: ExploreRoute,
  ImportRoute: ImportRoute,
  InspirationRoute: InspirationRoute,
  MyTripsRoute: MyTripsRoute,
  ParsingRoute: ParsingRoute,
  QuizRoute: QuizRoute,
  ShareRoute: ShareRoute,
  TripRoute: TripRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
